### ISSUE TITLE
Concurrent WaveBank updates

### ISSUE THREAD

**Issue by d-chambers** [niosh-mining/obsplus#114]
Currently the concurrent `WaveBank` update feature works well enough on our low-load system but is causing frequent failures with the CI. I think we need to move away from the naive locking mechanism I implemented to (optionally) allow a one process to both read and write to the index as in [this example](https://github.com/PyTables/PyTables/blob/master/examples/multiprocess_access_queues.py).

**Comment by sboltz** [comment]
I would certainly be in favor of this.

**Comment by d-chambers** [comment]
closed by #117
