### ISSUE TITLE
df_to_inv handling numeric NSLCs

### ISSUE THREAD

**Issue by sboltz** [niosh-mining/obsplus#130]
We have a case where we will do temporary deployments and all of the networks, stations, locations, and channels are numeric. When reading a csv file containing the station information, pandas will automatically interpret these columns as floats. As a result, when it gets passed to `df_to_inv` the NSLCs get interpreted as '1.0', '2.0', and '3.0' instead of '1', '2', and '3'.

While it is not that difficult for the user to just make sure the data types are correct prior to passing the dataframe to the `df_to_inv`, it would be convenient to be able to have `df_to_inv` handle this natively to reduce time spent chasing down obscure bugs.

I played around with explicitly casting the dtypes for these columns to `str` prior to building the inventory, but if the columns are already interpreted as floats, it still has the same problem. The only solution that I can think of is to check if these columns are numeric and then to cast them first to `int` and then to `str` if they are, but this feels a little bit clunky.

Does anyone have any thoughts of a cleaner way to handle this?

**Comment by sboltz** [comment]
Actually, this appears to be a slightly more elegant solution:
`df['location'].astype(str).str.replace(".0", "")`

**Comment by d-chambers** [comment]
Seems like that should work. Is there any possibility it will interfere with legitimate names?

**Comment by sboltz** [comment]
I don't know... I don't think so just because I don't think that's a string you would expect to encounter in the specs for station names. Then again, I'm pretty sure single digit numeric codes also aren't the spec.

**Comment by d-chambers** [comment]
closed by #132
