### ISSUE TITLE
Updated time in EventBank is wrong

### ISSUE THREAD

**Issue by sboltz** [niosh-mining/obsplus#146]
It looks like there is a units problem with the updated time in the `EventBank`, not sure if it extends to the `WaveBank`.

I just tried `EventBank.get_event_summary()` and for the 'updated' column the times are on the order of "1970-01-01 00:00:01.575655063", which looks like it is interpreting a timestamp in seconds as nanoseconds.

My guess is it's probably a pretty easy fix, but I'm not sure what the implications are for updating the bank's index.

**Comment by d-chambers** [comment]
Yes, it sounds more like a simple fix for interpreting the banks index, hopefully we can avoid requiring any migrations/reindexing.

**Comment by d-chambers** [comment]
closed by #147
