### ISSUE TITLE
Remove support for `WaveBank` inventory

### ISSUE THREAD

**Issue by d-chambers** [niosh-mining/obsplus#152]
Currently `WaveBank` allows passing an `obspy.Inventory` to keyword `inventory` in its constructor. This allows `attach_response` to work in `get_waveforms`. However, since this behavior is being discouraged in ObsPy we should probably remove this option from `WaveBank`. Any objections?

**Comment by sboltz** [comment]
I have no real preference.

**Comment by d-chambers** [comment]
closed by #147
