### ISSUE TITLE
Unable to set no path structure on EventBank

### ISSUE THREAD

**Issue by sboltz** [niosh-mining/obsplus#178]
* obsplus version: master
* Python version: 3.7.4
* Operating System: Ubuntu 16.04

### Description
Currently, there is no way to specify that you do not want to use a path structure for an EventBank. 

### What I Did
I tried just specifying an empty string for the `path_structure' kwarg, but because this gets interpreted as false, EventBank is overriding it.

```
In [1]: import obsplus                                                                                        

In [2]: bank = obsplus.EventBank(".", path_structure="")                                                      

In [3]: bank.path_structure                                                                                   
Out[3]: '{year}/{month}/{day}'
```

Fixing this should simply be a matter of explicitly checking for None, rather than just checking if the path_structure is True (a non-empty object) or False.

**Comment by d-chambers** [comment]
What's the use case where you don't want a path_structure?

**Comment by sboltz** [comment]
Working with a small number of events that are unorganized in a folder. 

To be honest, I just happened to uncover a bug while being lazy.

**Comment by d-chambers** [comment]
> Working with a small number of events that are unorganized in a folder.

Wait, so shouldn't the `path_structure` only come into play when you call `put_events` or was it preventing it from indexing the directory?
