### ISSUE TITLE
Incorrect start_date and end_date for network in df_to_inventory

### ISSUE THREAD

**Issue by sboltz** [niosh-mining/obsplus#188]
* obsplus version: 0.1.0
* Python version: 3.7.6
* Operating System: Ubuntu 18

### Description
When generating an inventory from a DataFrame, the network `start_date` and `end_date` is set to the `start_date` and `end_date` to the first item that matches the network in the DataFrame. This is problematic because if that item starts before or ends after the life of the network, then the inventory object will subsequently ignore that network when retrieving data if the given time falls outside of that time range.

**Comment by d-chambers** [comment]
closed by #190
