### ISSUE TITLE
Issue with python 3.8 and obspy

### ISSUE THREAD

**Issue by sboltz** [niosh-mining/obsplus#203]
* obsplus version: v0.1.1+13.gbd2392c
* Python version: Python 3.8.3 (Anaconda 07.2020)
* Operating System: Ubuntu 16.04.3 LTS

### Description

I'm not sure if this is necessarily a bug that we can do anything about, but it is at least something I wanted to bring up. I just installed obsplus on a fresh install of Anaconda (Python 3.8) and when I went to import it got the following: `ImportError: Could not load shared library "libmseed_Linux_64bit_py38.cpython-38-x86_64-linux-gnu.so"`

This is actually an obspy error, but I feel like it's important to mention here because it occurred when the setup for obsplus installed obspy.

### What I Did

1. Installed the latest version of Anaconda
2. Installed obsplus from the cloned repository via the following command: `pip install -e .`
3. During the setup, obsplus installed obspy 1.2.2 (presumably from pip?)
4. Ran obsplus' test suite and got the following Traceback:
```
ImportError while loading conftest '{home_directory}/Gits/obsplus/tests/conftest.py'.
tests/conftest.py:19: in <module>
    import obsplus.utils.dataset
obsplus/__init__.py:13: in <module>
    from obsplus.events.json import json_to_cat, cat_to_json, cat_to_dict
obsplus/events/__init__.py:4: in <module>
    from .get_events import get_events
obsplus/events/get_events.py:15: in <module>
    import obsplus.utils.geodetics
obsplus/utils/__init__.py:4: in <module>
    from obsplus.utils.misc import iterate, yield_obj_parent_attr
obsplus/utils/misc.py:31: in <module>
    from obspy.io.mseed.core import _read_mseed as mread
../../anaconda3/lib/python3.8/site-packages/obspy/io/mseed/core.py:21: in <module>
    from . import (util, InternalMSEEDError, ObsPyMSEEDFilesizeTooSmallError,
../../anaconda3/lib/python3.8/site-packages/obspy/io/mseed/util.py:24: in <module>
    from .headers import (ENCODINGS, ENDIAN, FIXED_HEADER_ACTIVITY_FLAGS,
../../anaconda3/lib/python3.8/site-packages/obspy/io/mseed/headers.py:22: in <module>
    __clibmseed = _load_cdll("mseed")
../../anaconda3/lib/python3.8/site-packages/obspy/core/util/libnames.py:112: in _load_cdll
    raise ImportError(msg)
E   ImportError: Could not load shared library "libmseed_Linux_64bit_py38.cpython-38-x86_64-linux-gnu.so"
E     Path: {home_directory}/anaconda3/lib/python3.8/site-packages/obspy/lib/libmseed_Linux_64bit_py38.cpython-38-x86_64-linux-gnu.so
E     Current directory: {home_directory}/Gits/obsplus
E     ctypes error message: {home_directory}/anaconda3/lib/python3.8/site-packages/obspy/lib/libmseed_Linux_64bit_py38.cpython-38-x86_64-linux-gnu.so: wrong ELF class: ELFCLASS32
E     Directory listing of lib directory:
E       -, ., /, /, /, /, /, /, /, /, 3, 3, 8, _, a, a, a, a, a, b, b, b, c,
E       c, d, e, e, e, e, g, h, h, i, i, i, i, i, k, l, l, m, n, n, n, o, o,
E       o, o, p, p, p, s, s, s, s, t, t, t, w, y, y
```

Installing obspy from conda using `conda install -c conda-forge obspy` installed obspy-1.2.2-py38h8790de6_0, which resolved the issue.

**Comment by d-chambers** [comment]
Ya this looks more like an ObsPy issue. If you pip install ObsPy with a fresh copy of Conda on 3.8 do you get the same issue?

**Comment by sboltz** [comment]
I don't want to mess with the python install on the computer I was using. However, I just tried on my machine (Ubuntu 18.04) and I am not able to reproduce the original problem.

**Comment by sboltz** [comment]
All right, I went ahead and did it on the original computer. First I made a fresh copy of Conda and verified I could reproduce the original issue (I could). Then I tried reinstalling Conda, then installed ObsPy from pip before installing ObsPlus. Same issue.

**Comment by d-chambers** [comment]
Maybe this has been fixed? I went ahead and created a new conda env with the command

```bash
conda create -n test_obsplus numpy "python=3.8"
conda activate test_obsplus
pip install obsplus
```

Then I was able import obsplus.utils.misc without issue.

I am going to close for now as I don't think there is anything we can do in ObsPlus to fix the issue if it still exists anyway but feel free to re-open.

**Comment by sboltz** [comment]
Sounds good. As you say, it's not really anything we can fix.
