### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by d-chambers** [niosh-mining/obsplus#206]
A reminder to look at ways to improve the documentation including:
- Typos, wording
- Search-ability (maybe move to read the docs?)
- more

Most of these comments were made by @Gymbob as he went through the tutorials.

**Comment by shawnboltz** [comment]
- [ ] One of the things that could be clarified is working with a dataset on disk vs. one of the ObsPlus built-in datasets.
- [ ] Step 5 of the WaveBank tutorial returns something different than what actually happens?

**Comment by d-chambers** [comment]
Although the documentation is still far from perfect, #217 closes this particular issue.
