### ISSUE TITLE
Not throwing error on unknown variable

### ISSUE THREAD

**Issue by Gymbob** [niosh-mining/obsplus#207]
* obsplus version: 0.1.1
* Python version: 3.7.4
* Operating System: Unbuntu

### Description

while trying to get gaps and uptime as well as get_availability_df it doesn't throw an error when a variable is misspelled,  In this case the second 't' is missing in starttime.  The output displays all the data from the start of the index to the endtime.

### What I Did
bank.get_availability_df(startime=stime, endtime=etime)
bank.get_gaps_df(startime=stime, endtime=etime)

**Comment by shawnboltz** [comment]
This is ultimately a problem with `read_index` where it swallows unsupported kwargs. Here is a complete working example:
With the typo:
```
In [1]: import obsplus

In [2]: ds = obsplus.load_dataset("crandall_test")

In [3]: ds.waveform_client.read_index(startime="2020-01-01", endtime="2020-01-02
   ...: ")[["starttime", "endtime"]]
Out[3]: 
                     starttime                    endtime
0   2007-08-06 08:48:30.014000 2007-08-06 08:49:40.004000
1   2007-08-06 08:48:30.024998 2007-08-06 08:49:40.000000
2   2007-08-06 08:48:30.012000 2007-08-06 08:49:40.002000
3   2007-08-06 08:48:30.015000 2007-08-06 08:49:40.005000
4   2007-08-06 08:48:30.025000 2007-08-06 08:49:40.000000
..                         ...                        ...
394 2007-08-06 01:44:38.825000 2007-08-06 01:45:48.800000
395 2007-08-06 01:44:38.825000 2007-08-06 01:45:48.800000
396 2007-08-06 01:44:38.825000 2007-08-06 01:45:48.800000
397 2007-08-06 01:44:38.812000 2007-08-06 01:45:48.802000
398 2007-08-06 01:44:38.824998 2007-08-06 01:45:48.799998

[399 rows x 2 columns]
```
Without the typo:
```
In [5]: ds.waveform_client.read_index(starttime="2020-01-01", endtime="2020-01-0
   ...: 2")[["starttime", "endtime"]]
Out[5]: 
Empty DataFrame
Columns: [starttime, endtime]
Index: []
```

@d-chambers Would the proper behavior be to have it raise if one of the kwargs is not a column in the index? Or did you have a reason for doing it this way?

**Comment by d-chambers** [comment]
It probably should raise an exception if the kwarg isn't used, but I don't know if the kwargs should be limited to columns in the index. For example, If I recall correctly, 'event_id' and 'eventid' are both supported.
