### ISSUE TITLE
Installing from conda insntalls wrong pydantic version

### ISSUE THREAD

**Issue by shawnboltz** [niosh-mining/obsplus#244]
**Description**
When installing obsplus from conda, it is downloading the version of pydantic on conda-forge, which is only 0.18.2 (the current version is 1.8.2). As a result, obsplus is unable to be imported because it cannot find pydantic's `root_validator` (introduced in version 1).

**To Reproduce**
Install a fresh version of Anaconda, install obsplus with `conda install -c conda-forge`. From a python shell `import obsplus` and it returns an `ImportError` stating that it cannot find `root_validator`

**Expected behavior**
The correct version of pydantic should get installed with obsplus so that it is possible to import.

**Possible Fix**
Would it work to just pin the version of pydantic to >= the latest version? (I see that they recently patched a security issue and wouldn't recommend going lower than that.)

**Versions (please complete the following information):**
 - OS: Windows 10
 - ObsPlus Version 0.2.0
 - Python Version 3.8.8
 - Conda Version 2021.05 (4.10.3)

**Comment by d-chambers** [comment]
I am a bit confused why this is the case. Conda forge lists pydantic v 1.8.2 [here](https://anaconda.org/conda-forge/pydantic). I think you are right about the versions. We would need to pin the conda-forge version [here](https://github.com/conda-forge/obsplus-feedstock/blob/master/recipe/meta.yaml) and obsplus' requirements.txt.

I will make the changes and create a minor version bump to re-trigger the conda builds.

**Comment by d-chambers** [comment]
I tested installing obsplus 0.2.0 on linux into a new python 3.8 conda env and that worked fine. This is probably a windows-specific issue.

**Comment by shawnboltz** [comment]
Weird. Yeah, it must be. I repeated it on two computers (images the same), so it wasn’t just a fluke or user error. Thanks.
________________________________

**Comment by d-chambers** [comment]
Ok it looks like conda has build 0.2.1, want to try again?

**Comment by d-chambers** [comment]
I just tested installing 0.2.1 on windows 10 with python 3.7 and it worked fine. I will close this for now, feel free to re-open if needed.

**Comment by sboltz** [comment]
All right. Thanks. I was going to try it tomorrow, but that should have fixed it.
