### ISSUE TITLE
Pandas 1.4 causing problem with df_to_inventory tests

### ISSUE THREAD

**Issue by sboltz** [niosh-mining/obsplus#249]
**Description**
It looks like pandas 1.4 introduced a subtle bug to `obsplus.utils.df_to_inventory` where it will unexpectedly delete values from the end_time column. It looks like there is something about the index slicing in `line 114 of obsplus.utils.stations` that is causing the problem, but I can't for the life of me figure out what it is.

As a temporary workaround, I'm going to pin the pandas version to <1.4.

**To Reproduce**
Install pandas 1.4 and run the test suite for obsplus. `tests/test_utils/test_stations_utils.py::TestDfToInventory::test_new` on the comparison of the input and output DataFrames. On the output df, the end date has been removed for three of the stations/channels.

**Expected behavior**
The end dates shouldn't be getting dropped.

**Versions (please complete the following information):**
 - OS: Ubuntu 16.04
 - ObsPlus Version: master ('v0.2.2+0.gcc65a25.dirty')
 - Python Version: 3.8.12

**Comment by d-chambers** [comment]
fixed by #252
