### ISSUE TITLE
Add ability to specify the location of a Bank path?

### ISSUE THREAD

**Issue by shawnboltz** [niosh-mining/obsplus#258]
**Is this discussion related to a problem? Please describe.**
Currently when an EventBank/WaveBank is initialized, it assumes that the index must reside in the top-level directory of the bank path. In the vast majority of scenarios, this is a reasonable assumption. However, I have an odd scenario where I need to initialize a WaveBank on a read-only directory of waveforms (files can be added by another user, but I cannot add/modify them) and so it will not be possible to create/update the index file.

**Describe the solution you'd like**
It should be possible to pass a keyword argument to the EventBank/WaveBank indicating the path where the index should be stored that defaults to the current behavior. This way the index could be created in a folder that I do have control over and I can just point the bank to the correct index.

**Describe alternatives you've considered**
We've also briefly considered adding logic where there could be some sort of designated location that index files can be stored in (such as in the user's home directory) or that could be designated by a configuration file of some sort. This would eliminate the need for adding an additional kwarg, but would require that designated location to exist and be accessible or would require finding a way to only have to pass that configuration to obsplus once so it doesn't have to be specified every time obsplus is imported. (Could a compromise be to have a designated spot for a config file and then if that won't work for whatever reason, the user would then specify a path to it? There should be relatively few cases where that is necessary)

**Comment by d-chambers** [comment]
> It should be possible to pass a keyword argument to the EventBank/WaveBank indicating the path where the index should be stored that defaults to the current behavior

Ok, so just to be clear, both banks would have a new parameter in their `__init__` method called `index_path` or maybe just `index` which would allow you to specify where the index file lives. The default value would be `None` which implies it lives at the top level of the bank directory. Is this what you had in mind?

**Comment by shawnboltz** [comment]
> > It should be possible to pass a keyword argument to the EventBank/WaveBank indicating the path where the index should be stored that defaults to the current behavior
> 
> Ok, so just to be clear, both banks would have a new parameter in their `__init__` method called `index_path` or maybe just `index` which would allow you to specify where the index file lives. The default value would be `None` which implies it lives at the top level of the bank directory (the current behavior). Is this what you had in mind?

Yes, exactly.
