### ISSUE TITLE
Read the Docs timeout issue

### ISSUE THREAD

**Issue by d-chambers** [niosh-mining/obsplus#26]
RTD keeps timing out when nbsphinx is building the documentation. When I run the docker image installing the anaconda env takes ~20 minutes so I suspect this is the problem but the log is less than useful.

**Comment by calum-chamberlain** [comment]
Have you considered using pip to set up your RTD env? I think RTD caches pip packages, and [not conda ones](https://github.com/rtfd/readthedocs.org/issues/3261) - so it might time out again the first time, but not after that.
Looks like conda env create takes about 9 minutes on RTD.

**Comment by d-chambers** [comment]
Good idea. I think there was a hangup with pytables when I first tried it, but it is worth looking into again.
