### ISSUE TITLE
API reference page not found

### ISSUE THREAD

**Issue by shawnboltz** [niosh-mining/obsplus#262]
It appears that the documentation site is a bit broken at the moment. In particular, the links for the "Full API Documentation" and "Module Index" are giving 404 errors.

They point to the following URLS:
https://niosh-mining.github.io/obsplus/versions/latest/api/obsplus.rst
https://niosh-mining.github.io/obsplus/versions/latest/py-modindex.html

Similarly, searching for the items of interest (in this case `WaveBank`) is only bringing up the quick reference page and not the full API reference?

**Comment by shawnboltz** [comment]
@d-chambers 

The way the website is built is once again out of my knowledge, but this smells like it's related to putting the code in the src folder in the package modernization PR?

**Comment by shawnboltz** [comment]
Fixed.

**Comment by d-chambers** [comment]
Judging by your commit that was it ;)

**Comment by shawnboltz** [comment]
> Judging by your commit that was it ;)

Indeed it was. It looks like there's another issue that is related to a version change of something (my initial guess is pandas) that I'm still trying to track down. Once I know the culprit, I'll open another issue.
