### ISSUE TITLE
Pydantic v.2 raises UserError

### ISSUE THREAD

**Issue by calum-chamberlain** [niosh-mining/obsplus#265]
**Description**
When installing obsplus from conda-forge (as of 21 July 2023), pydantic v.2 is installed. It looks like there were some breaking changes for v.2 that result in at least one error with obsplus. The error that I ran into is associated with (this usage error](https://docs.pydantic.dev/dev-v2/usage/errors/#root-validator-pre-skip).

**To Reproduce**
Create a new environment (as run):
```bash
conda create -n test python=3.9 obsplus
conda activate test
```
Then run the following python code:
```python
from obsplus import WaveBank
```

Resulting error:
```python
C:\Users\Calum\miniconda3\envs\test\lib\site-packages\pydantic\_internal\_config.py:261: UserWarning: Valid config keys have changed in V2:
* 'orm_mode' has been renamed to 'from_attributes'
  warnings.warn(message, UserWarning)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Calum\miniconda3\envs\test\lib\site-packages\obsplus\__init__.py", line 13, in <module>
    from obsplus.events.json import json_to_cat, cat_to_json, cat_to_dict
  File "C:\Users\Calum\miniconda3\envs\test\lib\site-packages\obsplus\events\json.py", line 11, in <module>
    import obsplus.events.schema as event_schema
  File "C:\Users\Calum\miniconda3\envs\test\lib\site-packages\obsplus\events\schema.py", line 246, in <module>
    class WaveformStreamID(_ObsPyModel):
  File "C:\Users\Calum\miniconda3\envs\test\lib\site-packages\obsplus\events\schema.py", line 256, in WaveformStreamID
    @root_validator()
  File "C:\Users\Calum\miniconda3\envs\test\lib\site-packages\pydantic\deprecated\class_validators.py", line 228, in root_validator
    raise PydanticUserError(
pydantic.errors.PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.

For further information visit https://errors.pydantic.dev/2.0.3/u/root-validator-pre-skip
```

**Expected behavior**
Imports should work, we should fix up obsplus for pydantic v.2 following the [migration guide](https://docs.pydantic.dev/dev-v2/migration/) when we have time, and probably push out a re-release of obsplus pinning to pydantic<2.0.

**Versions (please complete the following information):**
 - OS: [e.g. iOS] Windows 11
 - ObsPlus Version [e.g. 0.1.0] 0.2.4
 - Python Version [e.g. 3.8] 3.9

**Comment by d-chambers** [comment]
Thanks @calum-chamberlain, I will work on this in the next day or two. I think it should be straight-forward, ObsPlus isn't doing anything fancy with pydantic. We are long overdue for a release anyway.

**Comment by d-chambers** [comment]
Hey @calum-chamberlain,

Mind taking 0.2.5 for a spin? It pinned pydantic <2 and fixed a few other small issues.

While working on the pydantic v2 branch, I am finding the json serialization is orders of magnitude slower than with v1, so it may take me a while to get this fully upgraded. Moreover,  unless there is an immediate need for pydantic V2 support, I am inclined to let the pydantic folks do a few more bug fix releases first to see if the issue resolves.

**Comment by calum-chamberlain** [comment]
I'll have a gander this morning. Agree on letting the pydantic folks get some more bug fixes out of the way.

**Comment by calum-chamberlain** [comment]
Looks good to me. Thanks!

**Comment by calum-chamberlain** [comment]
Actually, a slight issue with 0.2.5 is that it is reporting the version number as 0.0.0 for me with a fresh install. This ends up re-building any banks that I have.

**Comment by d-chambers** [comment]
Ah yes. This is related to an issue with setuptools-scm and conda compatibility (eg see [this PR](https://github.com/pypa/setuptools_scm/pull/860)). I think we can just rebuild ObsPlus' conda recipe to be like [DASCore's](https://github.com/conda-forge/dascore-feedstock/blob/main/recipe/meta.yaml) and it should work.

**Comment by d-chambers** [comment]
Ok, just confirmed the new conda build fixed the version issue. Please reopen if you still run into problems.
