### ISSUE TITLE
obsplus.event.utils.make_origins() using bad picks

### ISSUE THREAD

**Issue by sboltz** [niosh-mining/obsplus#74]
* obsplus version: 0.0.1
* Python version: 3.7
* Operating System: Ubuntu 16.04

When using obsplus.events.utils.make_origins(), it will create a new origin based on the earliest pick regardless of phase_hint or evaluation_status. This is problematic if there is, for instance, a rejected pick, or a "noise" pick that was made some time before an event.

This can easily be remedied by adding a check to filter rejected picks and verify the pick is a valid waveform phase (not quite sure if the best route to fixing this is only blocking "noise" picks, or maybe allow a user-defined list of picks that by default contains "P" and "S" for the phase hint?)

**Comment by d-chambers** [comment]
> allow a user-defined list of picks that by default contains "P" and "S" for the phase hint

Good idea. I would also be in favor of just looking for P picks or else raising an exception, but a custom list might be useful on occasion.

**Comment by d-chambers** [comment]
closed by #76
