### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by dsiervo** [niosh-mining/obsplus#8]
* Python version: 2.7
* Operating System:  elementary OS 0.4.1 Loki (ubuntu 16.04 LTS)

### Description

Hi, when I tried to install obsplus through the command "pip install obsplus" the following error was generated:

```
Command "python setup.py egg_info" failed with error code 1 in / tmp / pip-install-eMsRqw / obsplus /
```

In a similar way when I tried to install it with the commands:

```
git clone https://github.com/niosh-mining/obsplus
cd obsplus
pip install.
```

The following error was generated:

```
Command "python setup.py egg_info" failed with error code 1 in / tmp / pip-req-build-w2D42P /
```

**Comment by calum-chamberlain** [comment]
A quick google suggests that maybe your [setuptools is out of date](https://github.com/facebook/prophet/issues/418).
Can you try running:
```bash
pip install --upgrade setuptools
```
then re-try installing?

**Comment by d-chambers** [comment]
Hi @dsiervo,

This library actually doesn't support python 2. You need python 3.6+. I will work on catching any such issues and issuing an intelligible error message. 

That being said, can you try installing it in a python 3.6+ virtual env?

**Comment by dsiervo** [comment]
> Hi @dsiervo,
> 
> This library actually doesn't support python 2. You need python 3.6+. I will work on catching any such issues and issuing an intelligible error message.
> 
> That being said, can you try installing it in a python 3.6+ virtual env?

I installed it in python 3.7 and it works fine. Thanks.
