### ISSUE TITLE
npts inconsistencies likely arising from float32->float64 cast

### ISSUE THREAD

**Issue by El-minadero** [niosh-mining/obsplus#87]
Ok team,

I think I've found the source of the npts issue. It likely arises from how .sac stores the sampling rate as a single precision float. Based on [this](https://github.com/obspy/obspy/issues/2402) discussion over at ObsPy, it looks like the endtime calculated from the 'delta' header after obspy reads in a sac file becomes slightly inaccurate. So if wavebank is used to query a sub waveform, the returned waveforms may have inconsistent npts even if the source files have the 'same' initial sampling rate.

I'm not sure if this is an issue appropriate to address within obsplus, but it might prudent to at least document this behavior.

**Comment by d-chambers** [comment]
I am not sure how you would go about "fixing" this within obsplus, except by forcing int sampling rates, which would not be wise. I suppose in the `update_index` methods you might have an option to coerce the sampling rates to integers, but that seems a bit dirty to me. I can add a note in the docstring of `WaveBank.get_waveforms` that this can happen depending on the file format you are using.

**Comment by El-minadero** [comment]
When you create a Wavebank from a list of stations, is obspy behind the scenes reading the files in? or do you use another parser?

**Comment by d-chambers** [comment]
WaveBank's index is created from a *directory of waveform files* (no station data other than what is contained in the file headers) using [this](https://github.com/niosh-mining/obsplus/blob/a97ffb67c94a1730ed134eea61848a5e96f994ec/obsplus/bank/utils.py#L72) function. For mseed it has a bit of an optimization, but for sac files it is essentially just using `obspy.read(path, headonly=True)`.

**Comment by El-minadero** [comment]
Would it make sense to add functionality to assign/set metadata to stations via obsplus interfaces rather than relying on the underlying files to have the correct headers?

**Comment by d-chambers** [comment]
Maybe, what would it look like? 

Personally I would just read each file, set the correct stats, and convert it to mini seed unless you are really space constrained.

**Comment by El-minadero** [comment]
Yeah I suppose for the UUSS uses, the mseed approach is quicker. But I do forsee circumstances where querying index could be useful. perhaps something like
````python
wavebank = Wavebank()
"""
add stuff to wavebank
"""
df= wavebank.get_metadata(**kwargs)
```
setting the metadata could then be done in a similar way
````python
wavebank = Wavebank()
"""
add stuff to wavebank
"""
wavebank.set_metadata(**kwargs)
```

**Comment by d-chambers** [comment]
I could see how this could be useful but it presents some architectural challenges as `WaveBank` doesn't store any station metadata. If you call `WaveBank.read_index()` the dataframe returned is all the state the bank has (except for a version string and a last-updated timestamp). It would be difficult to add station data because it would require an additional table in HDF5 index and the station data can change over time. 

As a side note I have been meaning to create a `StationBank` but I haven't gotten around to it yet.

**Comment by El-minadero** [comment]
@d-chambers what have you envisioned StationBank to be like?

**Comment by d-chambers** [comment]
`StationBank` will behave just like `EventBank` and `WaveBank`; it will index a directory of station-like objects (typically stationxml) and allow the user to treat return inventory objects with the `get_stations` method. It will also have a `read_index` method if you just want to see the "metadata" (starttime, endtime, position, etc.)

**Comment by El-minadero** [comment]
Interesting. Well I'm willing to help create this!

**Comment by d-chambers** [comment]
Hey @El-minadero, I am going to close this for now. It really is more of an issue with the (mis)use of SAC files and probably falls outside the scope of obsplus. If you have any ideas, however, that would  not require drastic rewrites or nasty hacks feel free to re-open.
