### ISSUE TITLE
Use Pandas datetime 

### ISSUE THREAD

**Issue by d-chambers** [niosh-mining/obsplus#88]
We should look into using pandas datetime to represent all time columns in obsplus dataframes. 

Pros
------
1. Human readable
2. Efficient
3. Pandas datetime niceties (ie datetime methods)
4. It is more "pandonic" 

Cons
-------
1. May break existing code (not sure how much)
2. May run into issues representing years before 1678 and after 2262 (https://github.com/pandas-dev/pandas/issues/7307)

**Comment by calum-chamberlain** [comment]
I'm keen on this, even just from the standpoint of making the time columns human readable. About the cons:
1. Unsure how much code would be broken either.  For what it is worth it wouldn't break any of mine. Might be worth having a branch trying it and asking people that you know have code that depends on it to see if anything breaks?
2. Waveforms need nanosecond precision, which limits the range of dates supported to 1678-2262, but I don't think stations or events need that level of precision - I know none of my origin times are accurate to the nanosecond, nor my station start and end times. So:
  - For stations and events we could use microsecond precision giving a larger range;
  - I don't know of any seismic data pre 1678, and I think we can safely assume that there will be other favoured languages in ~150 years time, so nanoseconds for waveform times could be fine.

**Comment by d-chambers** [comment]
Closed by #131
