### ISSUE TITLE
NoneType object is not iterable, problem in utils.py with opening sparse wavebank.

### ISSUE THREAD

**Issue by El-minadero** [niosh-mining/obsplus#9]
Python 3.6.5

### Description
First off, great job with this repo! It's simplified so many tasks and allowed me to get down to doing real research!

I ran into an error while processing some ambient noise data that perhaps you could point some fixes to. It seems when I try and load a sparse wavebank, I get " TypeError: 'NoneType' object is not iterable "

### What I Did
 using the debugger tool I narrowed it down to line 210 in utils.py. Seems like pandas.read_hdf is getting something it doesn't like. For reference, it's receiving self.bank.index_path ('which i confirmed to be an existing file path'), self.bank._index_node (which seems to have the value of '/waveforms/index',  a 'where' thing which is: 
```
starttime<9000000010.111000) | 
((endtime>-10.111000 & endtime<9000000010.111000) | 
(starttime<-10.111000 & endtime>9000000010.111000))
```
and a dict that upon inspection, seems like its a tuple? with columns ('network', 'station', 'location', 'channel', 'starttime', 'endtime'). 

This error popped up while I was trying to get waveforms from a single station named '1' (from a private dataset) via the call
```
 return self._processed_bank.get_waveforms(station=key)
```
I did confirm the bank did have the proper file system reference, wherein there should have only been 1 sac file named 0.sac. 

So is this a pandas problem or a obsplus problem I wonder? Im using pandas version 23.4.

**Comment by d-chambers** [comment]
Hmmm... not sure. Can you attach the index or provide more of the traceback? I am afraid it is not obvious what is going on and I will need a bit more context.

**Comment by El-minadero** [comment]
Nvm. Found the problem.

When there's an existing .index. file in the working directory that doesn't represent the current wavebank, the error occurs. Deleting the .index. file and calling Wavebank(base_path=<the base path>) seems to fix it. 

After updating my conda envs a bit, I also seem to not be able to reproduce the error.

**Comment by d-chambers** [comment]
Ok, closing for now. Feel free to re-open if it crops up again.
