### ISSUE TITLE
dfextractor interpreting Nones as 'None's

### ISSUE THREAD

**Issue by sboltz** [niosh-mining/obsplus#99]
* obsplus version: master
* Python version: 3.7.1
* Operating System: Ubuntu 16.04

### Description

There is a bug in the `DataFrameExtractor` where if an attribute of an object isn't populated, instead of returning `None` or an empty string, it returns the string `'None'`. Specifically noticed this when running `picks_to_df()` on a catalog that didn't have any polarity or onset information on the picks.

This is very trivial to fix, and, in fact, this fix is already done to correct `'nan'`. However, when I tried to implement the fix for `'None'` I ran into a problem in the tests for `events_to_df()` where one of the events in the Crandall dataset actually has an EventDescription that is set to `'None'`.

Thoughts on the best way to handle this @d-chambers?

**Comment by d-chambers** [comment]
@sboltz,
Yes we can just go ahead and change the description. I don't think anyone is relying on that exact event description. Just make sure to add something in the change log and we should be good.

**Comment by d-chambers** [comment]
closed by #100
